// pages/resume.vue
<template>
  <section class="container">
  <div>
    <name/>
    <div class="content">

      <h2 class="subtitle">
        Résumé
      </h2>

      <h4>Full-stack web application developer with over a decade of SAAS experience
      </h4>

      <ul>
        <li v-for="hl in highlights">
          {{ hl }}
        </li>
      </ul>

      <h3>Experience</h3>
      <div v-for="pos in work">

        <div class="row position-header">
          <div class="column column-50">
            {{ pos.company }}, {{ pos.location }}
          </div>
          <div class="column column-50 date-range">
              {{ pos.dateRange }}
          </div>
        </div>
        <div class="position-title">
          {{ pos.position }}
        </div>
        <div class="summary">
          {{ pos.summary }}
        </div>
      </div>

      <h3>Education</h3>
      <div v-for="pos in education">
        <div class="row position-header">
          <div class="column column-50">
            {{ pos.institution }}
          </div>
          <div class="column column-50 date-range">
              {{ pos.dateRange }}
          </div>
        </div>
        <div class="summary">
          {{ pos.studyType }}
        </div>
      </div>

      <SiteMenu></SiteMenu>
    </div>
  </div>
  </section>
</template>
<style scoped="">
  li {
    list-style-position: outside;
    margin-left: 16px;
  }
  .position-header {
    margin-top: 20px;
    font-weight: bold;
  }
  .position-title, .summary {
    margin-bottom: 10px;
  }
  @media (min-width: 40.0rem) {
    .date-range {
      text-align: right;
    }
  }
</style>

<script>
  import Name from '~components/Name.vue';
  import SiteMenu from '~components/SiteMenu.vue';
  import resumeData from './resume.json';

  export default {
    data () {
      return resumeData
    },
    components: {
      Name, SiteMenu
    }
  }
</script>

// src/pages/resume.jsx
import resumeData from './resume.json';
import Name from "../components/Name.jsx";
import styled from "styled-components";

const Wrapper = styled.div`
  li {
    padding-left: 16px;
    margin-top: .6rem;
  }
  .position-header {
    margin-top: 20px;
    font-weight: bold;
  }
  .position-title, .summary {
    margin-bottom: 10px;
  }
  @media (min-width: 40.0rem) {
    .date-range {
      text-align: right;
    }
  }
`;

export default () => {

    const { highlights, work, education } = resumeData;
    return (
    <Wrapper className="container mx-auto content-start px-4">
        <div>
            <Name />
            <div className="content mx-auto content-start px-4">

                <h2 className="subtitle">
                    Résumé
                </h2>

                <h4 className="text-xl mb-3">Full-stack web application developer with over a decade of SAAS experience
                </h4>

                <ul className="mb-3" style={{ listStyle: "circle inside" }}>
                    {highlights.map((hl, i) => (

                    <li className="leading-normal mb-2" key={i}>
                        {hl}
                    </li>
                        ))}
                </ul>

                <h3 className="text-2xl my-6">Experience</h3>
                {work.map((pos, i) => (
                    <div key={i}>
                        <div className="row position-header flex items-stretch">
                            <div className="flex-1 w-50">
                                {pos.company}, {pos.location}
                            </div>
                            <div className="flex">
                                {pos.dateRange}
                            </div>
                        </div>
                        <div className="position-title">
                            {pos.position}
                        </div>
                        <div className="summary">
                            {pos.summary}
                        </div>
                    </div>
                ))}

                <h3>Education</h3>

                {education.map((pos, i) => (
                    <div key={i}>
                        <div className="row position-header">
                            <div className="column column-50">
                                {pos.institution}
                            </div>
                            <div className="column column-50 date-range">
                                {pos.dateRange}
                            </div>
                        </div>
                        <div className="summary">
                            {pos.studyType}
                        </div>
                    </div>
                    ))}
            </div>
        </div>
    </Wrapper>
    )};
